In [8]:
import numpy as np
import cv2
# 用Numpy生成unit8格式的数组作为图片
img=np.zeros((3,3,),dtype=np.uint8)
print(img)

img=cv2.cvtColor(img,cv2.COLOR_GRAY2BGR)
print('将灰度图转BGR后的图片：\n',img)
##由此可看，每个像素由一个三原数组表示，并且每个整数向量分别表示一个B、G、R通道

print('图片的大小和通道数',img.shape)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
将灰度图转BGR后的图片：
 [[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
图片的大小和通道数 (3, 3, 3)


In [9]:
#保存改变图片的格式
img=cv2.imread('target.png')
cv2.imwrite('target.jpg',img)

True

# imread()函数的参数 
IMREAD_ANYCOLOR/ CV_LOAD_IMAGE_ANYCOLOR=4，其中添加了alpha,任何彩色，单独使用的时候等价于 IMREAD_UNCHANGED / CV_LOAD_IMAGE_UNCHANGED 。<br>
IMREAD_ANYDEPTH / CV_LOAD_IMAGE_ANYDEPTH=2 ：任何位深度，如果载入的图像不是16-bit位图或者32-bit位图，则转化为8-bit位图。<br>
IMREAD_COLOR / CV_LOAD_IMAGE_COLOR=1 ：图像转为彩色图（BGR，3通道）<br>
IMREAD_GRAYSCALE / CV_LOAD_IMAGE_GRAYSCALE=0 ：图像转为灰度图（GRAY，1通道）<br>
IMREAD_LOAD_GDAL=8<br>
IMREAD_UNCHANGED=-1<br>
##  无论采用哪种模式，imread()函数斗湖删除所有alpha通道的信息

In [13]:
# 方法一：转灰度图
grayImg=cv2.imread('target.jpg',cv2.IMREAD_GRAYSCALE)
#方法二：转灰度图
grayImg2=cv2.imread('target.jpg',0)
cv2.imshow('grayImg',grayImg)
cv2.imshow('grayImg2',grayImg2)
cv2.waitKey(0)
cv2.destroyAllWindows()

# 图像与原始字节之间的转换
一个像素通常由每个通道的一个字节表示<br>
8位的灰度图是二维数组，24位的BGR图片时三维数组
img[0,0,0],第一个代表y,第二个代表x,第三个代表通道

In [18]:
# 随机字节的bytearray转换为灰度图像和BGR图像
import cv2
import numpy as np
import os

# 生成一个120000随机字节的数组
randomByteArray = bytearray(os.urandom(120000))
# print(randomByteArray)
flatNumpyArray=np.array(randomByteArray)
# print(flatNumpyArray)

# 将数组转成一个400X300的灰度图片
grayImage=flatNumpyArray.reshape(300,400)

# 将数组转成400X100的彩色图片
bgrImg=flatNumpyArray.reshape(100,400,3)

cv2.imshow('grayImage',grayImage)
cv2.imshow('bgrImg',bgrImg)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [27]:
img=cv2.imread('target.jpg')
# 一个像素由一个包含三个元素的数组构成
print(img[0][0])

# 使用numpy.array访问图像数据
print(img.item(56,45,0))
img.itemset((56,45,0),0)
print(img.item(56,45,0))

cv2.imshow('img',img)

img[:,:,1]=0
cv2.imshow('改变后的图片',img)

img_roi=img[0:50,0:50]
cv2.imshow('img_roi',img_roi)
cv2.waitKey(0)
cv2.destroyAllWindows()

[255 255 255]
255
0


In [28]:
print('查看图片的宽，高和通道数：',img.shape)
print('查看图像像素的大小：',img.size)
print('查看图像的数据类型：',img.dtype)

查看图片的宽，高和通道数： (77, 89, 3)
查看图像像素的大小： 20559
查看图像的数据类型： uint8


# 视频文件的读写

videoWriter = cv2.VideoWriter('out.mp4', cv2.cv.CV_FOURCC('M', 'J', 'P', 'G'), fps, size)<br>

或

videoWriter = cv2.VideoWriter('out.avi', cv2.cv.CV_FOURCC('I','4','2','0'), fps, size)<br>

实际运行时生成的视频大小为0k，究其原因是运行环境没有相对应的视频编码器，故无法生成的视频，或者说第二个参数设置的不合适，系统里没有合适的。<br>

解决办法<br>

cv2.VideoWriter()第二个参数设置为-1，程序运行时则会交互地弹出一个对话框让你从系统已有的编码中选择一个。<br>
cv2.VideoWriter_fourcc('I','4','2','0')[YUY颜色编码]和cv2.VideoWriter_fourcc('P','I','M','1')[MPEG-1编码]是.avi格式<br>
cv2.VideoWriter_fourcc('X','V','I','D')[MPEG-4编码]是.avi格式<br>
cv2.VideoWriter_fourcc('T','H','E','O')[Ogg Vorbis]是.ogv格式<br>
cv2.VideoWriter_fourcc('F','L','V','1')[Flash]是.flv


In [31]:
import cv2

videoCapture=cv2.VideoCapture('Lara_UrbSeq1_CAOR_v3_7_HR.avi')
fps=videoCapture.get(cv2.CAP_PROP_FPS)
size=(int(videoCapture.get(cv2.CAP_PROP_FRAME_WIDTH)),int(videoCapture.get(cv2.CAP_PROP_FRAME_HEIGHT)))
videoWriter=cv2.VideoWriter('MYout.avi',cv2.VideoWriter_fourcc('I','4','2','0'),fps,size)
# videoWriter=cv2.VideoWriter('MYout.avi',-1,fps,size)
success,frame=videoCapture.read()
while success:
    videoWriter.write(frame)
    success,frame=videoCapture.read()


# 捕获摄像头的帧


In [5]:
import cv2
cameraCapture=cv2.VideoCapture(0)
# 设置帧率
fps=30
size=(int(cameraCapture.get(cv2.CAP_PROP_FRAME_HEIGHT)),int(cameraCapture.get(cv2.CAP_PROP_FRAME_HEIGHT)))
videowriter=cv2.VideoWriter('output.avi',cv2.VideoWriter_fourcc('I','4','2','0'),fps,size)
success,frame=cameraCapture.read()
print(success)
numFrameRemaining=10*fps-1
while success and numFrameRemaining >0:
    videowriter.write(frame)
    success,frame - cameraCapture.read()
    numFrameRemaining-=-1
cameraCapture.release()

False


# 在窗口显示摄像头帧

In [1]:
import cv2
clicked=False

def onMouse(event,x,y,flags,param):
    global clicked
    if event == cv2.EVENT_LBUTTONUP:
        clicked=True

cameraCapture=cv2.VideoCapture(0)
cv2.namedWindow('MyWindow')
cv2.setMouseCallback('MyWindow',onMouse)
print('显示窗口，单击窗口或者任意键退出')
success,frame=cameraCapture.read()
while success and cv2.waitKey(1) == -1 and not clicked:
    cv2.imshow('MyWindow',frame)
    success,frame=cameraCapture.read()
    
cv2.destroyAllWindows('MyWindow')
cameraCapture.release()

显示窗口，单击窗口或者任意键退出


SystemError: <built-in function destroyAllWindows> returned NULL without setting an error

In [4]:
if False and None is not None:
    print('A')
else:
    print('B')
    

B


In [10]:
assert not True

AssertionError: 

In [9]:
A=True
assert A == False

AssertionError: 

In [11]:
def testReturn():
    return
a=testReturn()
print(a)

None


In [21]:
class A(object):
    def __init__(self):
        self.a=3
        self.__a=5
    def printAns(self):
        print(self.a)
        print(self.__a)
    
    def returnSelf(self):
        return self._returnSelf
a=A()
a.printAns()
a.returnSelf
# a.a
# a.__a

3
5


<bound method A.returnSelf of <__main__.A object at 0x0000000005C72710>>

In [ ]:
_enteredFrame
_enteredFrame